// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSiteAPI.Models.EFModels
{
    public partial class AnimalType
    {
        public AnimalType()
        {
            Adoptions = new HashSet<Adoption>();
        }

        public int AnimalTypeId { get; set; }
        public string AnimalType1 { get; set; }

        public virtual ICollection<Adoption> Adoptions { get; set; }
    }
}