// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSiteAPI.Models.EFModels
{
    public partial class MemberCoupon
    {
        public MemberCoupon()
        {
            ProductOrders = new HashSet<ProductOrder>();
        }

        public int MemberCouponId { get; set; }
        public int MemberId { get; set; }
        public int CouponId { get; set; }
        public bool UsedCoupon { get; set; }
        public bool Status { get; set; }
        public int? Qty { get; set; }

        public virtual Coupon Coupon { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<ProductOrder> ProductOrders { get; set; }
    }
}