// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSiteAPI.Models.EFModels
{
    public partial class ParentCategory
    {
        public int ParentCategoryId { get; set; }
        public string Name { get; set; }
        public int ProductCategoryId { get; set; }
    }
}