// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSiteAPI.Models.EFModels
{
    public partial class ProductImage
    {
        public int ProductImageId { get; set; }
        public int ProductNameId { get; set; }
        public string Images { get; set; }

        public virtual ProductName ProductName { get; set; }
    }
}